import "./globals.css";
import { Poppins } from "next/font/google";
import Providers from "./providers";
import { Navbar } from "./Component";
const poppins = Poppins({ weight: "300", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className="lavender-dark">
      <body className={`${poppins.className} bg-dark` }>
        <Providers>
          <Navbar />
          <main className='container mx-auto max-w-7xl pt-16 px-6 flex-grow'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
